# Generated by Django 3.2 on 2022-02-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='action',
            name='logo',
            field=models.FileField(default='img/activities.png', null=True, upload_to='img/'),
        ),
    ]
