# Generated by Django 3.2 on 2022-02-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20220201_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='date',
        ),
    ]
