# Generated by Django 3.2 on 2022-02-04 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='logo',
            field=models.FileField(default='img/unknown.png', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='budget.action'),
        ),
    ]
