# Generated by Django 3.2 on 2022-02-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_action_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='budget.action'),
        ),
    ]
