# Generated by Django 3.2 on 2022-02-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_journal_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='logo',
            field=models.FileField(default='img/unknown.png', null=True, upload_to='img/'),
        ),
    ]
