# Generated by Django 3.2 on 2022-02-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_journal_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['date']},
        ),
    ]
