# Generated by Django 3.2 on 2022-02-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_alter_journal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
    ]
